from .seccion_viewset import SeccionViewSet, SeccionSerializer, SeccionDetailSerializer
from .cargo_viewset import CargoViewSet, CargoSerializer
from .recinto_viewset import RecintoViewSet, RecintoSerializer, RecintoDetailSerializer
from .mesa_viewset import MesaElectoralViewSet, MesaElectoralSerializer, MesaElectoralDetailSerializer
from .jurado_viewset import JuradoViewSet, JuradoSerializer
from .eleccion_viewset import EleccionViewSet, EleccionSerializer
from .candidatura_viewset import CandidaturaViewSet, CandidaturaSerializer
from .papeleta_viewset import PapeletaViewSet, CandidaturaSimpleSerializer, CargoConCandidatosSerializer, PapeletaSerializer 