# Generated by Django 5.2.4 on 2025-07-08 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Recinto',
                'verbose_name_plural': 'Recintos',
            },
        ),
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('foto_carnet_anverso', models.ImageField(upload_to='carnet_anverso/')),
                ('foto_carnet_reverso', models.ImageField(upload_to='carnet_reverso/')),
                ('foto_votante', models.ImageField(upload_to='votantes/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votantes', to='electoral.recinto')),
            ],
            options={
                'verbose_name': 'Votante',
                'verbose_name_plural': 'Votantes',
            },
        ),
    ]
