# Generated by Django 5.2.4 on 2025-07-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votante',
            name='recinto',
        ),
        migrations.AddField(
            model_name='votante',
            name='recinto_id_externo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Recinto',
        ),
    ]
