# Generated by Django 5.2.4 on 2025-07-09 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MesaElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Mesa Electoral',
                'verbose_name_plural': 'Mesas Electorales',
                'ordering': ['recinto', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('ubicacion', models.CharField(help_text='Dirección o ubicación del recinto', max_length=300)),
            ],
            options={
                'verbose_name': 'Recinto',
                'verbose_name_plural': 'Recintos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('ci', models.CharField(help_text='Cédula de identidad del jurado', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurados', to='administracion_electoral.mesaelectoral')),
            ],
            options={
                'verbose_name': 'Jurado',
                'verbose_name_plural': 'Jurados',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.AddField(
            model_name='mesaelectoral',
            name='recinto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='administracion_electoral.recinto'),
        ),
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRESIDENCIAL', 'Presidencial'), ('DEPARTAMENTAL', 'Departamental'), ('MUNICIPAL', 'Municipal'), ('JUDICIAL', 'Judicial'), ('LEGISLATIVA', 'Legislativa')], max_length=20)),
                ('fecha', models.DateField()),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elecciones', to='administracion_electoral.seccion')),
            ],
            options={
                'verbose_name': 'Elección',
                'verbose_name_plural': 'Elecciones',
                'ordering': ['-fecha', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('secciones_afectadas', models.ManyToManyField(help_text='Secciones donde este cargo está en disputa', related_name='cargos', to='administracion_electoral.seccion')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_candidato', models.CharField(max_length=200)),
                ('partido_politico', models.CharField(max_length=150)),
                ('sigla', models.CharField(help_text='Sigla del partido político', max_length=20)),
                ('color', models.CharField(help_text='Color hexadecimal del partido (ej: #FF0000)', max_length=7, validators=[django.core.validators.MinLengthValidator(7)])),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='administracion_electoral.cargo')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['cargo', 'nombre_candidato'],
                'unique_together': {('nombre_candidato', 'cargo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='mesaelectoral',
            unique_together={('numero', 'recinto')},
        ),
    ]
