# Generated by Django 5.2.4 on 2025-07-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_electoral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='polygon',
            field=models.JSONField(blank=True, help_text='Coordenadas del polígono de la sección en formato GeoJSON', null=True),
        ),
    ]
