# Generated by Django 5.2.4 on 2025-07-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_electoral', '0002_seccion_polygon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recinto',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='recinto',
            name='capacidad',
            field=models.IntegerField(default=100, help_text='Capacidad máxima del recinto'),
        ),
        migrations.AddField(
            model_name='recinto',
            name='direccion',
            field=models.CharField(default='Sin dirección', help_text='Dirección del recinto', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recinto',
            name='horario_apertura',
            field=models.TimeField(default='08:00', help_text='Hora de apertura del recinto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recinto',
            name='horario_cierre',
            field=models.TimeField(default='18:00', help_text='Hora de cierre del recinto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recinto',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Latitud del recinto', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='recinto',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Longitud del recinto', max_digits=15, null=True),
        ),
    ]
