# Generated by Django 5.2.4 on 2025-07-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_electoral', '0003_remove_recinto_ubicacion_recinto_capacidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recinto',
            name='horario_apertura',
            field=models.TimeField(blank=True, help_text='Hora de apertura del recinto (formato: HH:MM)', null=True),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='horario_cierre',
            field=models.TimeField(blank=True, help_text='Hora de cierre del recinto (formato: HH:MM)', null=True),
        ),
    ]
