# Generated by Django 5.2.4 on 2025-07-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_electoral', '0004_alter_recinto_horario_apertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recinto',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Latitud del recinto', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Longitud del recinto', max_digits=20, null=True),
        ),
    ]
